name: Run Parking Script

on:
  schedule:
    - cron: '0 16 * * 0,2,3'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y curl jq

      - name: Make script executable
        run: |
          chmod +x scripts/main.sh
          bash scripts/main.sh "33917203" "Moha506090"

#      - name: Run script
#        env:
#          ID: ${{ secrets.CAR_ID }}
#          PASSWORD: ${{ secrets.DPM_PASSWORD }}
#        run: bash scripts/main.sh "33917203" "Moha506090"

#      - name: Send email with results
#        uses: dawidd6/action-send-mail@v3
#        with:
#          server_address: smtp.gmail.com  # Change if using another provider
#          server_port: 587
#          username: ${{ secrets.EMAIL_USERNAME }}
#          password: ${{ secrets.EMAIL_PASSWORD }}
#          subject: "Parking Script Results"
#          body: "Attached is the lo
